# Unlocking the Power of Numerical Computing

## Advantage of using Numpy over traditional Python lists

In [24]:
import numpy as np
import time as tm
from numpy.random import default_rng

In [25]:
size = 1000000

#Python List
list1 = range(size)
list2 = range(size)

#Numpy Array
array1 = np.arange(size)
array2 = np.arange(size)

#Time taken to operate using traditional python list
init_time = tm.time()

res = [a*b for a, b in zip(list1, list2)] #List Comprehension

print("Time taken to operate using traditional python lists = ", tm.time()-init_time, " seconds")


#Time taken to operate using numpy array
init_time =  tm.time()
res = array1*array2 #Broadcasting

print("Time Taken to operate using numpy array= ", tm.time()-init_time," seconds")

Time taken to operate using traditional python lists =  0.25315189361572266  seconds
Time Taken to operate using numpy array=  0.03309941291809082  seconds


# Section 1: Basics


## Creating Numpy Arrays

In [26]:
#Using Python List/tuple/array-like-structure
np.array([1,2,3])

array([1, 2, 3])

In [27]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [28]:
d3 = [
    [[1,2], [3,4]],
    [[5,6],[7,8]]
]

In [29]:
np.array(d3, dtype="float32")

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]], dtype=float32)

### 1D Array
```
  numpy.arange([start, ]stop, [step, ]dtype=None)
  numpy.linspace(start, stop, num=50)
```

In [32]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.linspace(1, 50, 20)

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

### 2D array
```
numpy.eye(N, M=None, k=0, dtype=<class 'float'>)
numpy.diag(v, k=0)
```

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.diag([1,2,3], k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

### 3D array
```
numpy.ones(shape, dtype=None)
numpy.zeros(shape, dtype=float)
```

In [46]:
np.ones((2,3))*2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Array with random values

In [52]:
x = default_rng(40).random((2,3))

In [53]:
x

array([[0.7298985 , 0.69341496, 0.94192102],
       [0.05965206, 0.69052097, 0.92239752]])

## Shape of an array

In [55]:
#Shape of an array
x.shape

(2, 3)

In [56]:
#Reshaping
x.shape = (6,1)

In [57]:
x

array([[0.7298985 ],
       [0.69341496],
       [0.94192102],
       [0.05965206],
       [0.69052097],
       [0.92239752]])

## Indexing, Slicing, Striding

In [58]:
#Indexing
x[1]

array([0.69341496])

In [59]:
#Slicing
x[1:5]

array([[0.69341496],
       [0.94192102],
       [0.05965206],
       [0.69052097]])

In [60]:
#Striding
x[1:6:2]

array([[0.69341496],
       [0.05965206],
       [0.92239752]])

# Section 2: Numerical Computation

## Broadcasting
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

* they are equal, or

* one of them is 1.

In [61]:
#Broadcasting
x = np.arange(1,4,1)
y = 2
x * y

array([2, 4, 6])

<img src="https://numpy.org/doc/stable/_images/broadcasting_1.png">
Source: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">NumPy</a>

In [62]:
x.shape

(3,)

In [67]:
x = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
y = np.array([1.0, 2.0, 3.0, 4.0])
x + y

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [68]:
x.shape= (3,4)

In [69]:
x+y

array([[ 1.,  2.,  3., 14.],
       [11., 12., 23., 24.],
       [21., 32., 33., 34.]])

<img src="https://numpy.org/doc/stable/_images/broadcasting_2.png">
Source: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">NumPy</a>

In [64]:
x.shape

(4, 3)

In [65]:
y.shape

(3,)

In [92]:
x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])

In [93]:
x

array([ 0., 10., 20., 30.])

In [79]:
x.shape

(4,)

In [80]:
y.shape

(3,)

In [81]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [94]:
x= x[:, np.newaxis]

In [95]:
x

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [97]:
x.shape

(4, 1)

In [100]:
x+y

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [99]:
(x + y).shape

(4, 3)

<img src="https://numpy.org/doc/stable/_images/broadcasting_4.png">
Source: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">NumPy</a>